package dregex

import dregex.impl.Dfa
import dregex.impl.SimpleState

/**
  * A regular expression that was generated by an operation between others (not parsing a string), so it lacks a
  * literal expression or NFA.
  */
class SynteticRegex private[dregex] (
    private[dregex] val dfa: Dfa[SimpleState],
    val universe: Universe
) extends Regex {

  override def toString = s"[synthetic] (DFA states: ${dfa.stateCount})"

}
