name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21 ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: build
        run: ./gradlew check

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log (Java ${{ matrix.java-version }})
          path: ${{ github.workspace }}/dregex-test.log
