name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 12, 13, 14, 15 ]
        scala-version: [ "2.11.12", "2.12.15", "2.13.6" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
      - run: sbt ++${{ matrix.scala-version }} -v +test