name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21 ]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          # The target JDK is used to build, the latest one to run Gradle itself (we cannot use Java 11 for Gradle)
          java-version: |
            ${{ matrix.java-version }}
            21

      - name: build
        run: ./gradlew check
        env:
          JAVA_TOOLCHAIN: ${{ matrix.java-version }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log (Java ${{ matrix.java-version }})
          path: ${{ github.workspace }}/dregex-test.log
